AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ApplicationQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 345600

Outputs:
  QueueUrl:
    Value: !Ref ApplicationQueue
